#!/bin/sh -e

. /etc/ros/robot-bringup

CATKIN_WS="/home/$USER/catkin_ws/install"
HOSTNAME="$(hostname)"

export ROS_DISTRO=noetic
export LD_LIBRARY_PATH="/opt/ros/$ROS_DISTRO/lib"
export PYTHONPATH="$CATKIN_WS/lib/python3/dist-packages:/opt/ros/$ROS_DISTRO/lib/python3/dist-packages"
export ROS_PACKAGE_PATH="$CATKIN_WS/share/:/opt/ros/$ROS_DISTRO/share"
export ROS_MASTER_URI="http://$HOSTNAME:11311"
export PATH="$PATH:$CATKIN_WS/bin:/opt/ros/$ROS_DISTRO/lib/systemd_ros"
export ROS_ROOT="/opt/ros/$ROS_DISTRO/share/ros"
export ROS_VERSION=1
export ROS_ETC_DIR="/opt/ros/$ROS_DISTRO/etc/ros"
export HOSTNAME

LOCAL_LAUNCH_FILE="$CATKIN_WS/share/$PACKAGE/launch/$LAUNCH_FILE"
LAUNCH_FILE="/opt/ros/$ROS_DISTRO/share/$PACKAGE/launch/$LAUNCH_FILE"
if [ -e "$LOCAL_LAUNCH_FILE" ]; then
    LAUNCH_FILE="$LOCAL_LAUNCH_FILE"
fi

generate-services "$SERVICE" "$LAUNCH_FILE" "$3" --user "$USER" --group "$GROUP" --extra-config="/etc/ros/robot-bringup-extras.yaml" > "/$3/$SERVICE-generator.out" 2>&1
mkdir -p "$3/multi-user.target.wants/"
ln -s "$3/$SERVICE.service" "$3/multi-user.target.wants/"
